# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{semlogger}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Denis Knauf"]
  s.date = %q{2012-09-17}
  s.description = %q{(Semi-)Structured Logger for Ruby (and Rails)}
  s.email = ["Denis.Knauf@gmail.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "AUTHORS",
    "LICENSE",
    "README.md",
    "VERSION",
    "lib/semlogger.rb",
    "lib/semlogger/filter.rb",
    "lib/semlogger/formatter.rb",
    "lib/semlogger/multiplex.rb",
    "lib/semlogger/rack.rb",
    "lib/semlogger/rotate.rb",
    "lib/semlogger/tailer.rb",
    "lib/semlogger/writer.rb"
  ]
  s.homepage = %q{http://github.com/DenisKnauf/semlogger}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{(Semi-)Structured Logger}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
  end
end

